### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [tum-vision/lsd_slam#10]
Some parameters (like "[${EIGEN3_INCLUDE_DIR}](https://github.com/tum-vision/lsd_slam/blob/af719c62194ef96a465926d0bbc6b0071098d885/lsd_slam_core/CMakeLists.txt#L75)" and "[${PROJECT_SOURCE_DIR}/thirdparty/Sophus](https://github.com/tum-vision/lsd_slam/blob/af719c62194ef96a465926d0bbc6b0071098d885/lsd_slam_viewer/CMakeLists.txt#L15)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by JakobEngel** [comment]
true, We never had any special caracters in our paths, as it tends to create problems anyway ;) -
could you send a respective pull-request? Thanks!
