### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [tum-vision/lsd_slam#11]
The build tool "CMake" supports also [parallel build trees](http://www.cmake.org/Wiki/CMake_FAQ#What_is_an_.22out-of-source.22_build.3F). I find statements like the following inappropriate [for this functionality](http://www.cmake.org/Wiki/CMake_Useful_Variables#Locations).
- [set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/bin)](https://github.com/tum-vision/lsd_slam/blob/af719c62194ef96a465926d0bbc6b0071098d885/lsd_slam_viewer/CMakeLists.txt#L17)
- [set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/lib)](https://github.com/tum-vision/lsd_slam/blob/af719c62194ef96a465926d0bbc6b0071098d885/lsd_slam_core/CMakeLists.txt#L16)

**Comment by JakobEngel** [comment]
how do you propose to resolve this, while keeping the old functionality?

**Comment by elfring** [comment]
I would prefer a strict separation between input and output directories.
If you would insist to modify contents in a source directory, such a detail could be configured with [another build option](http://www.cmake.org/cmake/help/v3.0/command/option.html).

**Comment by Dvad** [comment]
I am not sure it is possible to do that and keep the rosbuild system. (At least, I have not found how)
And, actually, it might not be worth it, since a port to catkin would allow out-of-source-builds.
