### ISSUE TITLE
Getting memory corruption while running data_slam

### ISSUE THREAD

**Issue by anuragajay** [tum-vision/lsd_slam#132]
![screenshot from 2015-08-05 19 16 20](https://cloud.githubusercontent.com/assets/6889348/9102430/fe88ced6-3ba6-11e5-8e41-31dc4040631b.png)
When I run data_slam on my dataset, I get memory corruption error. I have attached the screenshot for the error. Also, for purpose of testing, if I use LSD_room_images on data_slam, which camera calibration file should I use? Is it in LSD_room_images.zip itself or somewhere else?

**Comment by anuragajay** [comment]
Just an update. When I run dataset_slam with LSD_room Dataset, I get segmentation fault.
![screenshot from 2015-08-05 23 12 19](https://cloud.githubusercontent.com/assets/6889348/9104988/86052074-3bc7-11e5-8901-02e780e3a672.png)

**Comment by anuragajay** [comment]
Figured the error

**Comment by mihaibujanca** [comment]
@anuragajay what was the problem? How did you solve it?

**Comment by kungfrank** [comment]
Is there any one know how to solve this error?
