### ISSUE TITLE
How to save/generate the .ply file of live LSD-SLAM?

### ISSUE THREAD

**Issue by aartikanungo** [tum-vision/lsd_slam#149]
hello,
I Got .bag files and .ply fils in examlpes. 
I wanted to know that how to save .ply file when i use live lsd-slam?

**Comment by LEETZUNGYOU** [comment]
hello
did u find the answer about that ?
because I have the same issue!

**Comment by aartikanungo** [comment]
Hello @LEETZUNGYOU, when you run lsd-slam on your system, just select pointcloud viewer window and press p for long time. you will get the .ply (pc.ply) file in your lsd-slam viewer folder... open it on meshlab.. hope it works :)

**Comment by LEETZUNGYOU** [comment]
Thank you for your answer

Date: Mon, 2 Nov 2015 01:32:58 -0800

**Comment by Irenedvs** [comment]
@aartikanungo is there anyway we could do it by code rather than a shortcut key
