### ISSUE TITLE
Tracking issues?

### ISSUE THREAD

**Issue by gpdaniels** [tum-vision/lsd_slam#15]
When moving in a circle (in this picture) the graph seems to think I'm moving tangentially along a wall, and the point cloud is literally a cloud.

![lsd-slam broken](https://cloud.githubusercontent.com/assets/1503387/4419544/24423734-456c-11e4-96a1-07201c056a47.png)

Actually, it seems no matter how I move it always seems to think I'm translating. The red constraint lines means that the constraints were bad, and if I add a print of the number of contraints added at then end of findConstraintsForNewKeyFrames(...) the number is 2 for the first 10 or so updates then, predominately 0 with the occasional 1 or 2 (when I start revisiting known keyframes)

Thought this might be partially due to not having openFABMAP but adding that made no difference. 

Could g2o have changed internally? (I'm using a build from their github)

My only other thought is that it's being caused by a bad camera calibration. Which is quite possible as the PTAM calibrator refuses to go below about 2 RMS pixel error for this camera.

**Comment by gpdaniels** [comment]
Also occasionally getting:
terminate called after throwing an instance of 'Sophus::ScaleNotPositive'
  what():  Sophus exception: Scale factor is not positive

**Comment by JakobEngel** [comment]
Hmm, looks like it's not working at all - do the displayed color-coded depthmaps look correct? 
As you mentioned, this is probably due to a (very) bad camera calibration (RMSE should not be above 0.5) - maybe the lens you are using introduces radial distortion, which cannot be modelled properly by the FOV model used by PTAM.

**Comment by gpdaniels** [comment]
I've run a few of the provided sequences though it now and get a similar cloud output even. So it's not (only) my bad camera calibration. Something is very wrong. I'm currently doing a fresh install to see if that works.

And yes, the colour coded depth map seems good, and the first pointcloud from the first keyframe looks correct.

**Comment by gpdaniels** [comment]
Ok so another update. I've finally managed to get a version working. Although weirdly the desk sequence wouldn't work and kept losing tracking. Maybe it's due to my use of live_slam vs dataset.

So this didn't work:
rosrun lsd_slam_core live_slam image:=/image_raw camera_info:=/camera_info
and
rosbag play ~/LSD_room.bag

While this did work:
rosrun lsd_slam_core dataset_slam _files:=/path/to/images _hz:=50 _calib:=/path/to/cameraCalibration.cfg

The only difference between this ros version and my version is that I forced it to use the ros version of g2o although I haven't checked that was the culprit yet.

Weird.

**Comment by gpdaniels** [comment]
After fighting with cmake for a while I now have LSD-SLAM compiling with the correct libraries at last. It seems some combination of ros's g2o and the git version were conflicting, but not enough to crash things.

Also, the tracking seems to fail on the first few frames a lot of the time if running in debug mode.

**Comment by gpdaniels** [comment]
Ok so LSD-SLAM is now running correctly, both ros version from here, and my heavily hacked standalone version. Even with a camera calibration that has an rms error of >2pixels. 

Just be sure that it is linking to the correct libraries.

My setup if anyone else was wondering:
- Ubuntu 14.04
- qt5
- git version of g2o
- git version of opencv (3.0 alpha)
- google code version of openFABMap
- git version of sophus

Modifications:
- removed the cv_bridge dependency from cmake and added my own version of opencv.
- edited a few source files to make LSD-SLAM and openFABMap compile with the new opencv.
- edited the git version of sophus to match yours after I realised that the version you provide has been edited.
