### ISSUE TITLE
Issues Initializing/ Mapping point cloud,

### ISSUE THREAD

**Issue by HyperLethalVector** [tum-vision/lsd_slam#17]
Greetings,

I'm attempting to get LSD-SLAM running so that I may intergrate it into my research,

I'm using Ubuntu 14.04 with the ros system Indigo,
And I'm pipelining my monochrome image into lsd_slam_core, however, I'm greeted with  

damien-r@waffleiron:~/ros_packages/lsd_slam$ rosrun lsd_slam_core live_slam image:=/image_mono _calib:=pinhole_example_calib.cfg
Reading Calibration from file pinhole_example_calib.cfg ... not found!
 Trying /home/damien-r/ros_packages/lsd_slam/lsd_slam_core/calib/pinhole_example_calib.cfg ... found!
found ATAN camera model, building rectifier.
Input resolution: 640 480
In: 0.527334 0.827306 0.473568 0.499436 0.000000
NO RECTIFICATION
Output resolution: 640 480
Prepped Warp matrices
Started  constraint search thread!
Started mapping thread!
Started optimization thread 
Doing Random initialization!
init done 
opengl support available 
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
Done Random initialization!
TRACKING LOST for frame 367 (0.01% good Points, which is 100.00% of available points, DIVERGED)!

Only sometimes does the image initialize properly (about 0.2 percent of the time) usually the output window freezes.

I'm unsure the reason why, and would like some help,

Thanks for the patience ^_^

**Comment by gpdaniels** [comment]
One thing I had issues with is that Qt will not allow it's GUI windows to be split over multiple threads. Whereas other GUI systems that OpenCV can use will. (Which is what LSD-SLAM assumes.)

It's clear that your version of OpenCV is using Qt for it's GUI from that output.

If you look through the code you can see that the first cv::imshow(...) is on the LiveSLAMWrapper thread. via debugDisplayDepthMap(...) from the call in randomInit() in SlamSystem.h, while the next is on a doMappingIteration(...) in the mappingThreadLoop(...) thread.

Aka either you need to recompile OpenCV without Qt as it's GUI system, or you need to disable the output windows by setting: "bool displayDepthMap = false;" in settings.cpp

Afraid this won't help with the failure to initialise, I found that framerate and light level made a significant impact on my setup.

**Comment by HyperLethalVector** [comment]
Interesting, I find that If I mash a button just after the initialization process begins, it works fine, including the output window, I even get a nice point cloud map.

Perhaps there is some threading issue in initialization?

**Comment by JakobEngel** [comment]
I added a separate thread for image display - now, cv::imshow is only called from one thread.
There is a static bool in ImageDisplay_OpenCV.cpp which you can use to go back to the old, multi-threaded version (which might be slighly better for performance).
Please try if that fixed the issue, or introduced more bugs :)

**Comment by K1lroy09** [comment]
Hi,

I seem to be struggling with similar display issues. The point cloud viewer seems to be only showing the red camera model and not the trajectory nor the point cloud. This behaviour persists even with the new version of the code. 

The poses published will suffice for merging the implementation into my evaluation framework, but a visual would also be nice :) 

Any help would be greatly appreciated.

**Comment by HyperLethalVector** [comment]
Greetings,

Now there is no debug display window, nor is the point cloud working at all,
It was working better with the previous code,

I apologize for the annoyance ^_^ 
Clive_slam: /usr/include/boost/thread/pthread/condition_variable_fwd.hpp:81: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
This appears after exiting if that helps.
