### ISSUE TITLE
Camera calibration problem using Matlab Toolbox

### ISSUE THREAD

**Issue by scottybit** [tum-vision/lsd_slam#181]
Recently I was trying the LSD_SLAM, using "Camera Calibration Toolbox for Matlab" to compute the intrinsic coefficients. However, the coefficients seemed to have large error, since I calibrated the camera multiple times. I was wondering, is the coefficients from matlab toolbox applicable? Must I use PTAM cameracalibrator to obtain the fx,fy,cx,cy...?

**Comment by sharder-dev** [comment]
You don't have to use Matlab for that. There are some alternatives such as an [opencv sample](https://github.com/Itseez/opencv/tree/master/samples/cpp/tutorial_code/calib3d/camera_calibration) (usable as a standalone) or simply [GML](http://graphics.cs.msu.ru/en/node/909).
