### ISSUE TITLE
TX1 has something wrong with lsd_slam_viewer?

### ISSUE THREAD

**Issue by tsingjinyun** [tum-vision/lsd_slam#191]
I have sucess make lsd_slam on Nvida Tx1,and could run example and my dasaset ,but  the lsd_slam_viewer just show a dark window and can't show any pointcloud? do any one come over this problem, thanks for any given suggestion!!!

**Comment by sandmen** [comment]
Hi tsingjinyun,
currently working also on TX1 and SLAM.
I will setup today the lsd_slam. Are there some "special" settings, changes needed ?

By the way, the RTAB-MAP is working fine for me on the TX1.

**Comment by tsingjinyun** [comment]
If you meet any questions,write here i will give my solution as far as i can,you may change the CMakelist to suit arm architecture

**Comment by amiltonwong** [comment]
I have only Tk1, does it also suitable for LSD-SLAM?

**Comment by sandmen** [comment]
Hmm, didn't find currently where the lsd-slam is define the videostab.so.2.4.8.
On TX1 we have 2.4.12, I need to change this some where... in Cmake or make.

**Comment by sandmen** [comment]
Ok, sucking now on g2o/core/base_vertex.h files....
Any hints

**Comment by tsingjinyun** [comment]
@amiltonwong ，I think it maybe ok,it just different in CPU,TK1 &Tx1 cpu core is just 4 ,this maybe a problem

**Comment by tsingjinyun** [comment]
@sandmen did you change lsd_slam/lsd_slam_core/CMakeLists? about line 44,
"${CMAKE_CXX_FLAGS} ${SSE_FLAGS} -march=armv8-a  -std=c++0x"
and any other thing you change it ?

**Comment by sandmen** [comment]
@tsingjinyun 
yes, did it. The main problem was, that the g2o lib was not installed :-(
And I need to disable SSE !! Do you also remove the "add_definitions("-DENABLE_SSE")" ?

**Comment by tsingjinyun** [comment]
@sandmen yes,need to disable SSE(which is intel X86 architecture),so it seem that u didn't install g2o,try  apt-cache search ros-indigo-libg2o ,can u find it?
then run this commond sudo apt-get install ros-indigo-libg2o.

**Comment by sandmen** [comment]
yes, install the bin. I try before to compile from source the g2o.
I try to use the ZED 3D cam with ld_slam, but currently hanging on calibration....

**Comment by dcs0002** [comment]
How did you resolve the black screen on the lsd_slam_viewer. 

I have everything running fine on TK1 and the viewer shows that it is receiving keyframes but the viewer itself remains black.

**Comment by tngan** [comment]
@amiltonwong Did you successfully build this package on TK1 ?

**Comment by tianwailaike** [comment]
@tsingjinyun Have you solved this problem, I also encountered this problem.The lsd_viewer is totally black and couldn't show any pointcloud.

**Comment by mtisz** [comment]
Having the same issue on TX2 - any of you managed to resolve this issue?
