### ISSUE TITLE
Generated pose is quite different from groundtruth of tum benchmark

### ISSUE THREAD

**Issue by johnny871227** [tum-vision/lsd_slam#192]
Hi,
I ran the lsd_slam on tum rgbd slam benchmark (e.g. fr3/teddy) and save the camera pose using "rostopic echo -p /lsd_slam/pose > my_pose" as suggested in #65 . However the saved pose looks quite different from the groundtruth provided by the benchmark. I also saved values from camToWorld.data() from KeyFrameDisplay.cpp and I got another set of different values. Take the pose of 1 frame as an example:

groudtruth gives: 
% tx ty tz qx qy qz qw
-2.1837 0.6821 1.4854 -0.2651 0.7889 -0.5183 0.1970 

"rostopic echo -p /lsd_slam/pose > my_pose":
%field.pose.position.x,field.pose.position.y,field.pose.position.z,field.pose.orientation.x,field.pose.orientation.y,field.pose.orientation.z,field.pose.orientation.w
-0.0152150429785,-0.00334000820294,0.0126420026645,0.00267713794262,0.00718338269731,-0.00229388124385,0.999967984515

camToWorld.data():
0 0 0 1 0 0 0 

Anyone got a clue why they are so different? 

Thanks,
Johnny

**Comment by LiangliangGuo** [comment]
Hi
I want to know if you have solved the question? if you do, please let me know, thakns!
