### ISSUE TITLE
lsd_slam using mobile phone

### ISSUE THREAD

**Issue by johnny871227** [tum-vision/lsd_slam#197]
On [https://www.youtube.com/watch?v=GnuQzP3gty4](url), lsd_slam is running on a mobile phone (from 22sec). Now I'm trying to use Samsung Galaxy S6 as a webcam (lsd_slam is still on a PC).  I use the DroidCam app on Ubuntu 14.04, and its works fine for capturing video on cheese and guvcview viewer. 
However I cannot use it as a livecam for lsd_slam. When running `rosrun uvc_camera uvc_camera_node device:=/dev/video0` I got errors shown below:

```
 [ INFO] [1463023869.895450013]: camera calibration URL: file:///home/xudi/rosbuild/package_dir/camera_umd/uvc_camera/example.yaml
opening /dev/video0
pixfmt 0 = 'YU12' desc = 'Planar YUV 4:2:0'
  discrete: 640x480:   1/30 
terminate called after throwing an instance of 'std::runtime_error'
  what():  couldn't set format
[1]+  Killed                  guvcview -d /dev/video0
Aborted (core dumped)

```

Anyone has a clue? I guess it's kinda related to #46 , but here I'm using a mobile phone to replace the webcam.

**Comment by johnny871227** [comment]
Btw, this may be a general problem for all webcam.

**Comment by johnny871227** [comment]
I just commented the line `throw std::runtime_error("couldn't set format");` in uvc_cam.cpp and  problem solved.

**Comment by caap95** [comment]
@johnny871227 , I can't find that file, uvc_cam.cpp. Can you tell me where it is
