### ISSUE TITLE
how use variable baseline to  calculate  inverseDepth

### ISSUE THREAD

**Issue by tsingjinyun** [tum-vision/lsd_slam#203]
hi,everyone:
in the  .../src/DepthEstimation/Depth.cpp, in doLineStereo() function,
https://github.com/tum-vision/lsd_slam/blob/master/lsd_slam_core/src/DepthEstimation/DepthMap.cpp#L1874
the author use  idnew_best_match = (dot0 - oldX*dot2) / nominator; 
and i think this used 1/z=d/fB (where f is the focal length,B is the baseline,z is the pixel depth),then the question come here:
i find it hard to match this formula. anybody come across this problem, thanks for your explanation

**Comment by tsingjinyun** [comment]
@JakobEngel，the alpha is  the length of the searched inverse depth interval and  the length of the searched epipolar line segment ratio，
https://github.com/tum-vision/lsd_slam/blob/master/lsd_slam_core/src/DepthEstimation/DepthMap.cpp#L1896
and those lines codes is very important to calculate depth and variance, any mathematics inference behind it?

**Comment by HeYijia** [comment]
Hi @tsingjinyun ,  I think I find it out.  It can be derived from the formula of  the projection of a 3D  world point into a camera image.  If have any question, let me know, GOOD LUCK.
![qq 20160818094752](https://cloud.githubusercontent.com/assets/11751752/17759385/3df5ec00-6529-11e6-9fdd-3c65bcadd0c6.png)

**Comment by tsingjinyun** [comment]
Thanks, I have figure it out. Thanks,anyway

发自 网易邮箱大师
On 08/18/2016 09:52, HeYijia wrote:

Hi @tsingjinyun , I think I find it out. It can be derived from the formula of the projection of a 3D world point into a camera image. If have any question, let me know, GOOD LUCK.
