### ISSUE TITLE
TRACKING LOST for frame x (x = small number) and "cholesky failed!"

### ISSUE THREAD

**Issue by siims** [tum-vision/lsd_slam#21]
I read your recommendations about having CCD, fps, not rotating/moving sideways and wide angle lens. My initial setup was things I had laying around (ps3 eye) and unfortunately tests showed that algorithm wasn't capable of tracking. 

There were two main problems what program indicated:

> TRACKING LOST for frame 34 (0.00% good Points, which is -nan% of available points, DIVERGED)!

and quite frequent...

> int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int*): cholesky failed!
> Cholesky failure, writing debug.txt (Hessian loadable by Octave)
> terminate called after throwing an instance of 'Sophus::ScaleNotPositive'
>  what():  Sophus exception: Scale factor is not positive
> Aborted (core dumped)

I was wondering might I be doing something wrongly or/and my problems come from my setup (is there any hope getting lsd_slam to work with ps3 eye -> cmos, 30 fps and not wide angle (75 deg))?

All help appreciated.

**Comment by JakobEngel** [comment]
sounds like it's diverging entirely - which shouldn't happen with careful motion and sufficiently structured / textured environment, even with a relatively unsuited camera. 
Maybe your calibration is bad?  If you send me a .bag of an example sequence, I can have a look at it.

**Comment by siims** [comment]
Here is bagfile (https://dl.dropboxusercontent.com/u/4148558/OpenCV_example_calib.cfg) and calibration (https://dl.dropboxusercontent.com/u/4148558/2014-10-17-12-23-19.bag).

**Comment by JakobEngel** [comment]
hmm, that bagfile contains a 10s video of a stationary camera... there is not much to reconstruct.

**Comment by siims** [comment]
Ok, I think I am doing something totally wrong. I tried out provided dataset from http://vision.in.tum.de/research/lsdslam and I am having the same trouble with the "Desk Sequence" bagfile.
I shortly describe what I am doing, maybe this helps you to understand where I am failing:
1) run lsd_slam "rosrun lsd_slam_core live_slam image:=/image_raw camera_info:=OpenCV_example_calib.cfg"
2) hold camera (30fps, rolling shutter, fov 75 deg angle) in my hand, press 'r' while moving camera in the same image plane (have tried sideways, vertical and circular motions).
... and with this depth map doesn't converge.

Something I leave undone? Do wrong?

**Comment by JakobEngel** [comment]
for the desk sequence you should use the camera calibration included tin the .bag, and not the OpenCV_example_calib.cfg. i.e., run
rosrun lsd_slam_core live_slam image:=/image_raw 
rosbag play LSD_room.bag

**Comment by siims** [comment]
It has been a while... but anyway, I got back to it and I confirm that it was camera calibration problem. After I parsed my values to PTAM configuration format then things started to work magically. I also made a pull request: https://github.com/tum-vision/lsd_slam/pull/34
Thank you very much for help :)

**Comment by siims** [comment]
also now you can remove "[untested]" from README near OpenCV camera calibration file.
