### ISSUE TITLE
questions about post-process for the 3D mapping (*.ply)

### ISSUE THREAD

**Issue by amiltonwong** [tum-vision/lsd_slam#22]
Dear all,

I had some questions about post-process for the 3D mapping result which I saved as pc.ply file.
My plan is to load pc.ply using PCL (Point Cloud Library).  The following is my code for reading ply file:
# 
# include  <iostream
# include  <pcl/io/pcd_io.h
# include  <pcl/io/ply_io.h
# include  <pcl/point_types.h

int main (int argc, char*\* argv)
{
  pcl::PointCloudpcl::PointXYZI::Ptr cloud (new pcl::PointCloudpcl::PointXYZI);

  if (pcl::io::loadPLYFilepcl::PointXYZI ("pc.ply", _cloud) == -1) //_ load the file
  {
    PCL_ERROR ("Couldn't read file pc.ply\n");
    return (-1);
  }

  std::cout << "Loaded "
            << cloud->width \* cloud->height
            << " data points from file test.ply with the following fields: "
            << std::endl;
  for (size_t i = 0; i < cloud->points.size (); ++i)
    std::cout << "    " << cloud->points[i].x
              << " "    << cloud->points[i].y
              << " "    << cloud->points[i].z<< std::endl;

  return (0);
} 
# 

output result (parsing ply error)
# 

./ply_read 
[pcl::PLYReader] pc.ply:8: parse error
[pcl::PLYReader::read] problem parsing header!
[pcl::PLYReader::read] problem parsing header!
Couldn't read file pc.ply
# 

I think the parsing error due to the wrong pointcloud template. But I' m confused about which pointcloud template I should choose because  the format of the ply output of LSD_SLAM is not described clearly.  

Could  someone  give me some hints to fix it?
THX!

Best regards,
Milton

**Comment by JakobEngel** [comment]
hmm, not sure - possibly there is something wrong with the way I create the .ply (or the way PCL tries to read .ply) - I have only tested to load them into meshlab, which works fine.
maybe the easiest way is to have a look at the code that creates them, and just do the inverse of that ;).
see line 60-94 in
lsd_slam_viewer/src/KeyFrameGraphDisplay.cpp

**Comment by amiltonwong** [comment]
Thanks @JakobEngel for your suggestion.
I fix it using a more simple method. First import the ply file into meshlab and export it again. And now the new exported ply can be read successfully using previous pcl code. I think maybe the header format issue and I'll correct it in later time.
BTW, according to line 81 in file lsd_slam_viewer/src/KeyFrameGraphDisplay.cpp, it seems that the code is about to output the intensity of the voxel, but I cannot find any intensity value except xyz positions in the output file ply. Does the original code contain intensity value or not for generating the ply file?

Best regards,
Milton

**Comment by JakobEngel** [comment]
yes, the original .ply does contain intensity for each point, maybe re-saving it with meshlab removed the intensity.
