### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by mlowney** [tum-vision/lsd_slam#23]
While trying to install the system dependencies I get the following error:

"E: Unable to locate package libqglviewer-dev"

I am calling 
sudo apt-get install ros-indigo-libg2o ros-indigo-cv-bridge liblapack-dev libblas-dev freeglut3-dev libqglviewer-dev libsuitesparse-dev

from ~/rosbuild_ws/package_dir

Does any other software have to be downloaded to get the package? I am new to ROS so any help would really be appreciated.

**Comment by mhkabir** [comment]
Probably means that you don't have binaries for your platform. What
operating system are you running? Did you run apt-get update?

Check my issue #1 for instructions on how to separate the viewer from the
core and thus not need qglviewer.

You can run the lsd_slam viewer on another networked computer where
qglviewer is installable.

**Comment by mlowney** [comment]
We ran apt-get  update. Ended up that we did not enable restricted repositories.

**Comment by bsirmacek** [comment]
I have the same error. Are there other dependencies maybe?
Sure I did apt-get update as well.
