### ISSUE TITLE
Obtaining camera positions from .ply

### ISSUE THREAD

**Issue by jmrr** [tum-vision/lsd_slam#24]
Hi,

I'm still in my learning stages of ROS and SLAM but I am wondering if I there is a way of getting the coordinates for the camera from the generated .ply file.

I've got everything running and I'm able to output bags and .ply files from sequences of frames acquired with my calibrated camera. I also installed Meshlab and I'm able to display the point cloud but again don't seem to be able to retrieve the camera locations.

I remember from other multi-view geometry packages such as bundler that the output file showed clearly the location of each point, their intensities and the camera locations. The .ply shows a lot of gibberish and if I do as in issue #22 I still don't see anything in clear text.

Thanks a lot.

Regards,

J

**Comment by JakobEngel** [comment]
the .ply is only the pointcloud, and does not contain the camera poses. 
As LSD-SLAM produces vastly more points than keypoint-based BA systems like bundler, they are stored in binary format (-> significantly smaller files) - which I suppose the gibberish you refer to is :).

You can get the poses e.g. by adding the output in whichever format you require (e.g. to line 60-94 in KeyFrameGraphDisplay.cpp).

**Comment by yolingen23** [comment]
> the .ply is only the pointcloud, and does not contain the camera poses.
> As LSD-SLAM produces vastly more points than keypoint-based BA systems like bundler, they are stored in binary format (-> significantly smaller files) - which I suppose the gibberish you refer to is :).
> 
> You can get the poses e.g. by adding the output in whichever format you require (e.g. to line 60-94 in KeyFrameGraphDisplay.cpp).

I want to get coordinate data from lsd- slam. Can you share the code we will add to KeyFrameDisplay.cpp?
