### ISSUE TITLE
Structure of topics.

### ISSUE THREAD

**Issue by rbarthseas** [tum-vision/lsd_slam#25]
I have a question regarding the message structure that the live_slam node would like to receive. For example whilst launching: 

$ rosrun lsd_slam_core live_slam /image:=<yourstreamtopic> /camera_info:=<yourcamera_infotopic>

I assume the /image is a sensor_msgs::Image message format. But what about the /camera_info ?

Thanks!
Ruud

**Comment by artivis** [comment]
Hi rbarthseas,

camera_info is of type <a href="http://docs.ros.org/indigo/api/sensor_msgs/html/msg/CameraInfo.html">sensor_msgs/CameraInfo Message 

Cheers.

**Comment by rbarthseas** [comment]
Of course! I couldv'e reckoned that there was a standardized camera info message like the image message is too.

Thanks. :)
