### ISSUE TITLE
live_cam using internal computer camera

### ISSUE THREAD

**Issue by caap95** [tum-vision/lsd_slam#275]
Hello guys, 

I'm very knew on ROS, just started working on it and in my project I will use LSD SLAM. 

Following the steps indicated I managed to install everything and managed to run the program using dataset_slam, using images, and also managed to run the LSD_ROOM example provided. But now I need to run the program live, and for that I wanted to use the internal pc camera. But since I really don't have any experience with ROS I can't find how I can do that. 

Can someone give me any tips or guidelines? 

Thanks.

**Comment by kevin-george** [comment]
I did some work with ROS Kinetic + LSD SLAM.
You should be able to use these steps -> https://github.com/kevin-george/lsd_slam/wiki/LSD-SLAM-with-ROS-and-Ubuntu-16.04
