### ISSUE TITLE
calibration file for dataset_slam

### ISSUE THREAD

**Issue by oulusel** [tum-vision/lsd_slam#28]
Hello,

I am trying to use the dataset_slam use case of the algorithm but I lose tracking in a couple frames and the lsd_slam goes over rest of the images very fast. I believe my problem is creating the calibration file but I couldn't find a solution myself.

The calibration file is as follows (converted from yaml to ini for easier reading):

width
640
height
480

camera matrix
1055.37849 0.00000 315.68028 
0.00000 1053.85271 205.37223 
0.00000 0.00000 1.00000 

distortion
-0.51926 0.34129 0.00533 -0.00140 0.00000 

rectification
1.00000 0.00000 0.00000 
0.00000 1.00000 0.00000 
0.00000 0.00000 1.00000 

projection
1001.52264 0.00000 314.22782 0.00000 
0.00000 1022.16687 203.95875 0.00000 
0.00000 0.00000 1.00000 0.00000 

I create the calibration file LSD SLAM requires from the K matrix as mentioned so the calibration file I use during calling dataset_slam is:

1055.37848633721 1053.85270577403 315.680278553583 205.372229361795 0
640 480
none
640 480

What am I doing wrong?

I have the bag file of the same set of images, which seem to work for a couple hundred frames. That's why I think my problem is the calibration file. I would like to use the dataset_slam to test the hz=0 option.

Thanks,

**Comment by JakobEngel** [comment]
seems like you're ignoring the non-zero distortion coefficients. maybe try something like

1055.37848633721 1053.85270577403 315.680278553583 205.372229361795 -0.51926 0.34129 0.00533 -0.00140 0.00000 
640 480
none
640 480

Also, from those values I take it that your camera has a very narrow field of view - which will probably give you relatively poor / non-robust performance.

**Comment by oulusel** [comment]
Thanks for the reply Jakob, but using the calibration file you suggested results with the following error:

Reading Calibration from file ... found!
found OpenCV camera model, building rectifier.
Input resolution: 640 480
In: 1055.378540 1053.852661 315.680267 205.372223 -0.519260 0.341290 0.005330 -0.001400
NO RECTIFICATION
Output resolution: 640 480
OpenCV Error: Assertion failed (func != 0) in transpose, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp, line 2023
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp:2023: error: (-215) func != 0 in function transpose
Aborted (core dumped)

Using the keywords 'crop' or 'full' instead of 'none' makes the code execute successfully but the tracking is lost after a couple frames similar to using the calibration file without any distortions.

I believe I should be using the format with "e1 e2 e3 e4 0" as described in the readme file:

fx/width fy/height cx/width cy/height d
in_width in_height
"crop" / "full" / "none" / "e1 e2 e3 e4 0"
out_width out_height

 but I am not sure what the "d" parameter should be in this case. Using the following calibration file: 

1055.37848633721 1053.85270577403 315.680278553583 205.372229361795 0
640 480
-0.51926 0.34129 0.00533 -0.00140 0.00000
640 480

runs the code but again, I lost tracking after only the 3rd frame.

Also thank you for the suggestion on the lens field of view, I am looking into obtaining larger field of view lenses already but just wanted to test out the algorithm with the lenses I already have (45 and 60 degrees of field of vision).

Thanks,

**Comment by jmrr** [comment]
I've got this very same problem. I'm using OpenCV calibration parameters and if I follow the instructions as per the Readme.md I get the same error:

what(): /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp:2023: error: (-215) func != 0 in function transpose

Is there a way of transforming the OpenCV calibration parameters to the ATAN ones? I've tried to calibrate my camera with the ptam ros package. However, as my camera is a smartphone one this is quite tricky.

How did you calibrate the mobile phone camera of your demo? I've managed to have my phone's camera as a v4l one under /dev/video0 but perhaps your experience on the calibration side can shed some light on the problem.

Thanks a lot.

**Comment by JakobEngel** [comment]
@onurcansel : 
Assuming your calibration accords to the OpenCV camera model, you should use
1055.37848633721 1053.85270577403 315.680278553583 205.372229361795 -0.51926 0.34129 0.00533 -0.00140
640 480
crop
640 480

@jmrr 
Same as above. Theoretically you can convert calibrations into one another, as all they do is approximate a radial mapping - with a polynomial in case of openCV, and with a one-parametric tangent function for the ATAN model. You could e.g. use matlab to do that, although you might have to look up the math ;). Also, not all cameras can be modelled equally well with all models; however for smartphone cameras which have little distortion, it's probably all the same.
We hacked the cameracalibrator from PTAM to operate on images, which we took with the smartphone.

**Comment by jmrr** [comment]
@JakobEngel Thanks a lot. I saw the cameracalibrator from PTAM and what I did was to set up my phone camera as a gscam webcam to get my ATAN camera model as I describe in this gist: https://gist.github.com/jmrr/0271f9f2186a695e6dae 

Your hacked PTAM is within ethzasl_ptam, right? Then maybe I should have guessed that it would work with the _files:= parameter...

**Comment by dmkt** [comment]
i actually prefer use that constructor:

``` c++
UndistorterOpenCV::UndistorterOpenCV(cv::Size inSize, const cv::Mat& cam, const cv::Mat& distCoeffs, double alpha, cv::Size outSize)
{
    if (outSize == cv::Size())
        outSize = inSize;
    originalK_ = cam;
    in_width = inSize.width;
    in_height = inSize.height;

    out_width = outSize.width;
    out_height = outSize.height;
    valid = true; //very unsafe! todo think more how correctly do that
    if (valid)
    {
        K_ = cv::getOptimalNewCameraMatrix(originalK_, distCoeffs, inSize, alpha, outSize, nullptr, false);

        cv::initUndistortRectifyMap(originalK_, distCoeffs, cv::Mat(), K_,
            cv::Size(out_width, out_height), CV_16SC2, map1, map2);

        originalK_.at<double>(0, 0) /= in_width;
        originalK_.at<double>(0, 2) /= in_width;
        originalK_.at<double>(1, 1) /= in_height;
        originalK_.at<double>(1, 2) /= in_height;
    }

    originalK_ = originalK_.t();
    K_ = K_.t();
}
```

if matrices came from same opencv itself it works perfectly

**Comment by giancan** [comment]
Sorry to re-open an old post but I am getting the exact same problem.
Here is how my config file looks like

1038.80915 935.492356 971.350044 587.037409 -0.34939748 0.17329119 0.00044628 -0.00183945 -0.05226159
1920 1080
full
640 480

I need to use it for a set of images (extracted from a video taken with an action camera).
Thanks,
G.
