### ISSUE TITLE
Support for Ubuntu16 with Kinetic

### ISSUE THREAD

**Issue by rnunziata** [tum-vision/lsd_slam#285]
Are there any plans to add  support for Ubuntu16 with Kinetic. 
At present there are too many issues to overcome for a working installation.

**Comment by hszhoushen** [comment]
You can follow the instruction as Ubuntu14, the only thing you need to change is to replace the indigo to the kinetic.

**Comment by rnunziata** [comment]
thanks

**Comment by johnchars** [comment]
[VisBot](http://visbot.blogspot.com/2014/11/tutorial-building-of-lsd-slam-on-ros.html)
May you can try catkin rather rosbuild.
