### ISSUE TITLE
How to evalute ORB-SLAM2 (and LSD-SLAM) on the TUM RGB-D Benchmark dataset? 

### ISSUE THREAD

**Issue by haidela** [tum-vision/lsd_slam#288]
Good evening, How to evalute Absolute Trajectory Error(ATE) using KITTI dataset or EuRoC on Matlab?

**Comment by MichaelGrupp** [comment]
Duplicate of https://github.com/raulmur/ORB_SLAM2/issues/454 - see my answer there...

**Comment by haidela** [comment]
@MichaelGrupp, thank you very much, it works well, as I am a beginner and I am trying to make my own ground truth

**Comment by MichaelGrupp** [comment]
ok, glad to help :+1:
