### ISSUE TITLE
LSD-SLAM to  Octomap

### ISSUE THREAD

**Issue by axelfar** [tum-vision/lsd_slam#304]
Hi ! 
I know that is possible to use Octomap with the lsd_slam point cloud.
But someone know how to send the point cloud to Octomap?  with ROS? 

Thanks :)

**Comment by Irenedvs** [comment]
@axelfar did you get the lsd_slam working with Octomap using ROS ?

**Comment by axelfar** [comment]
Hello @Irenedvs
Yes that works! 
I used this code :
https://github.com/Hypha-ROS/hypharos_ardrone_navigation

I use ROS Indigo with Ubuntu 14.04.

**Comment by Irenedvs** [comment]
thank you !
