### ISSUE TITLE
Issue running LSD_room.bag example

### ISSUE THREAD

**Issue by clauniel** [tum-vision/lsd_slam#31]
When executing: $ rosbag play ~/LSD_room.bag
the following happens.

OpenCV Error: Assertion failed (scn == 1 && (dcn == 3 || dcn == 4)) in cvtColor, file /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/color.cpp, line 3789
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/color.cpp:3789: error: (-215) scn == 1 && (dcn == 3 || dcn == 4) in function cvtColor

and kills the process.

I am on xubuntu 14.04.1.

EDIT: It might be relevant that this is happening in a virtualbox.

**Comment by JakobEngel** [comment]
hmm, that's strange. can you get a full stacktrace for that?

**Comment by romulogcerqueira** [comment]
I have the same error.

**Comment by clauniel** [comment]
This issue can be solved by disabling 3d and 2d acceleration in virtualbox.
