### ISSUE TITLE
[rosrun] Couldn't find executable named dataset_slam below {path to lsd_slam_core directory}

### ISSUE THREAD

**Issue by shehroze37-zz** [tum-vision/lsd_slam#32]
Hi 
live_slam seems to work fine on Ubuntu 14.04 but when I am trying to use the images from the LSD_room data set, Im getting this error 

[rosrun] Couldn't find executable named dataset_slam below {path to lsd_slam_core directory}

Any help with this  ? 

Cheers

**Comment by jmrr** [comment]
Hi,

I have been using the ROS executable `dataset` rather than `dataset_slam`.
I discovered this thanks to the autocomplete.

The call should read then:

`rosrun lsd_slam_core dataset _files:=/path/to/image/sequence _hz:=0
_calib:=/path/to/calibration/file.cfg`

**Comment by JakobEngel** [comment]
uhmm... yeah, I changed the binary name to dataset_slam.
