### ISSUE TITLE
liveframes vs. keyframes

### ISSUE THREAD

**Issue by rbarthseas** [tum-vision/lsd_slam#38]
Hi,

What is the difference between the message published on the /lsd_slam/keyframes and /lsd_slam/liveframes ?

Best,
Ruud

**Comment by rbarthseas** [comment]
In the source code I see that it is not filled with a pointcloud (see below). Hence only pointclouds are published at keyframes?

```
lsd_slam_viewer::keyframeMsg fMsg;

fMsg.id = kf->id();
fMsg.time = kf->timestamp();
fMsg.isKeyframe = false;

memcpy(fMsg.camToWorld.data(),kf->getScaledCamToWorld().cast<float>().data(),sizeof(float)*7);
fMsg.fx = kf->fx(publishLvl);
fMsg.fy = kf->fy(publishLvl);
fMsg.cx = kf->cx(publishLvl);
fMsg.cy = kf->cy(publishLvl);
fMsg.width = kf->width(publishLvl);
fMsg.height = kf->height(publishLvl);

fMsg.pointcloud.clear();

liveframe_publisher.publish(fMsg);
```

**Comment by amiltonwong** [comment]
@rbarthseas, did you see the corresponding paper? You can find the answer from it.

**Comment by rbarthseas** [comment]
Hi Amilton,

Thanks for pointing that out that reference. Will read!

Best,
Ruud
