### ISSUE TITLE
No Viewer, No map 

### ISSUE THREAD

**Issue by LiliMeng** [tum-vision/lsd_slam#39]
Hi,

```
 The compiling went well and there were no errors in the destop which installed Ubuntu14.04 and ROS indigo.

  I am using ASUS Xtion's monocular camera. So after executing $roslaunch openni_launch openni.launch and $ rosrun lsd_slam_core live_slam /image:=/camera/rgb/image_mono  /camera_info:=/camera/rgb/camera_info

  It displayed the following but without any map and viewer : 

  WAITING for ROS camera calibration!
```

Received ROS Camera Calibration: fx: 525.000000, fy: 525.000000, cx: 319.500000, cy: 239.500000 @ 640x480
RECEIVED ROS camera calibration!
Started  constraint search thread!
Started mapping thread!
Doing Random initialization!
Started optimization thread 
started image display thread!
Done Random initialization!
Fontconfig error: "/etc/fonts/conf.d/65-khmer.conf", line 14: out of memory
Fontconfig error: "/etc/fonts/conf.d/65-khmer.conf", line 23: out of memory
Fontconfig error: "/etc/fonts/conf.d/65-khmer.conf", line 32: out of memory
init done 
opengl support available 

The rqt_graph has displayed that /LSD_SLAM node has been connected with /camera/rgb/image_mono.

There is no map or viewer!  Could anyone figure out how to solve this problem? Thanks in advance!

**Comment by JakobEngel** [comment]
the 3d viewer is from lsd_slam_viewer, which you have to run also.
