### ISSUE TITLE
Tracking Lost after small number of frames, "Cholesky failure"

### ISSUE THREAD

**Issue by Bhargee** [tum-vision/lsd_slam#41]
The closed issue with the same problem does not seem to affect my case at all. I have calibrated an admittedly ill-suited camera (stock Logitech webcam, roughly 70 deg FOV, similar setup to [this guy](https://github.com/tum-vision/lsd_slam/issues/21)). I frequently get:

> TRACKING LOST for frame 34 (0.00% good Points, which is -nan% of available points, DIVERGED)!

When I can keep the algorithm running for longer (around a minute), it will fail with:

> int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int*): cholesky failed!
> Cholesky failure, writing debug.txt (Hessian loadable by Octave)
> terminate called after throwing an instance of 'Sophus::ScaleNotPositive'

I used the openCV camera calibrator, and my calibration file is as follows:

> 663.64 655.32 332.39 248.66 -0.0197 -0.123 0.0015 -0.0061
> 800 600
> crop
> 640 480

Any idea what is wrong?

**Comment by JakobEngel** [comment]
Hmm, what happened there is, that tracking gets completely lost and zero pixels are left, causing the optimization to diverge. 
That should actually not happen, and the tracker should just attempt to re-localize... at least then, it won't crash.
