### ISSUE TITLE
How to use my own dataset to do experiment?

### ISSUE THREAD

**Issue by zyzhong** [tum-vision/lsd_slam#45]
I installed lsd slam correctly and the LSD_room.bag example works well.  How to use video stream file e.g. mp4 to conduct experiment? And how to use AR Drone 2 to do live slam? Thanks in advance, any suggestion would be appreciate.

**Comment by oleg-alexandrov** [comment]
You'd split the movie into individual images and then follow the doc.

**Comment by JakobEngel** [comment]
as oleg suggested: the easiest would be to split the mp4 into individual image
