### ISSUE TITLE
no "LSDParamsConfig.h" and "LSDDebugParamsConfig.h" header

### ISSUE THREAD

**Issue by xieguotian** [tum-vision/lsd_slam#47]
when I compile LSD_SLAM, I got the error that :
/home/xieguotian/LSD_SLAM/src/lsd_slam/lsd_slam_core/src/IOWrapper/ROS/rosReconfigure.h:25:43: fatal error: lsd_slam_core/LSDParamsConfig.h: no such file or directory
 #include "lsd_slam_core/LSDParamsConfig.h"
How can I fix this error?

**Comment by JakobEngel** [comment]
the file should be auto-generated on "rosmake".

**Comment by nfnpmc** [comment]
How and what auto generates it?
I am using catkin_make. How do I adopt it?

**Comment by seedjack** [comment]
I meet the same question,how do I solve it ?

**Comment by JoelinChee** [comment]
i have met the same problem. How did you solve
It?

**Comment by wangcaimeng** [comment]
I find the two file on google and add them into this project.
