### ISSUE TITLE
lsd_slam_viewer error in roslaunch

### ISSUE THREAD

**Issue by simbaforrest** [tum-vision/lsd_slam#55]
First, thanks for your awesome work!

When I try to launch lsd_slam_viewer using roslaunch with the following launch file

``` xml
<launch>
  <node name="lsd_slam_viewer" pkg="lsd_slam_viewer" type="viewer"
        output="screen">
  </node>
</launch>
```

roslaunch throw the following error:

> process[lsd_slam_viewer-2]: started with pid [5219]
> Started QApplication thread
> terminate called after throwing an instance of 'rosbag::BagIOException'
>   what():  Error opening file: __log:=/home/simbaforrest/.ros/log/c1b907b4-961a-11e4-bf23-100ba9beb87c/lsd_slam_viewer-2.log
> [lsd_slam_viewer-2] process has died [pid 5219, exit code -6, cmd >/home/simbaforrest/bot/fuerte_ws/lsd_slam/lsd_slam_viewer/bin/viewer __name:=lsd_slam_viewer __log:=/home/simbaforrest/.ros/log/c1b907b4-961a-11e4-bf23-100ba9beb87c/lsd_slam_viewer-2.log].
> log file: /home/simbaforrest/.ros/log/c1b907b4-961a-11e4-bf23-100ba9beb87c/lsd_slam_viewer-2*.log
> ^C[rosout-1] killing on exit

I investigated the **main_viewer.cpp** a bit and found that the `ros::init(argc, argv, "viewer");` was called inside the `rosFileLoop` and `rosThreadLoop` which caused the problem because roslaunch add an extra input argument __name:=lsd_slam_viewer, thus the following code

``` c++
    if(argc > 1)
    {
        rosThread = boost::thread(rosFileLoop, argc, argv);
    }
    else
    {
        // start ROS thread
        rosThread = boost::thread(rosThreadLoop, argc, argv);
    }
```

will always start rosFileLoop instead of rosThreadLoop.

I guess it should be safe to move the `ros::init` into the `main` function and it did help resolve the issue.

**Comment by JakobEngel** [comment]
agreed, that is a somewhat unclean switch between file playback and live operation. thanks!
