### ISSUE TITLE
PointCloud Viewer window shows only the moving camera but no point cloud

### ISSUE THREAD

**Issue by hiankun** [tum-vision/lsd_slam#64]
Hi, I have tried to run lsd_slam for several days but still got no successful result, and I need some suggestions to find out where the problem is.

The issue I've encountered is that the code seemed keeping running (and it also lost tracking frequently, but it's might be another issue), and **the moving camera was shown in the `PointCloud Viewer` window. However, no point cloud was shown.** The following screenshot shows my result (I changed the code to alter the camera line color):

![lsd_slam_viewer_camera_only](https://cloud.githubusercontent.com/assets/7351282/5848985/22ab7aa6-a21a-11e4-91bf-1fa6018351c9.png)

Even when I followed the [Quickstart instruction](https://github.com/tum-vision/lsd_slam#1-quickstart--minimal-setup) to run lsd_slam with LSD_room.bag file, the results were all the same (it lost tracking at random frame, around after 1000th frame).

I traced the source code with `printf` and found the program always touched the following part in `KeyFrameDisplay::drawPC()`:

```
if (! vertexBufferIdValid )
{
    return ;
}
```

Also, when I pressed `Ctrl-w` on `PointCloud Viewer` window when lsd_slam was running with LSD_room.bag, the terminal always returned

```
Have 0 points, 0 keyframes, 0 constraints. Displaying 0 points.
```

So the program generated no point cloud, even when the tracking was still working?

At least I should get some reasonable results with the LSD_room.bag example, but I didn't. Did I miss something essential? I need some hints and helps from you. Thank you.

**Comment by ghemann** [comment]
I had the same problem.  Turns out it is actually an issue with QT windows for OpenCV, which other threads have mentioned, but seemed to be showing different problems.

The real problem is that cvWaitKey in OpenCV never returns even with a positive delay value in there, and so the doMappingIteration thread essentially blocks (meaning no creation of new keyframes).

Work around for me is removing the key input for the window.  Quickest easiest solution as opposed to reinstalling OpenCV.  If you need to use key inputs for the debug window, I'd say write your own debug method, or wait until OpenCV fixes that QT window error.

**Comment by hiankun** [comment]
I have left this topic for a long time... I would retry the code if I have some leisure time.

Thank you for the reply. :-)

**Comment by gitunit** [comment]
@ghemann can you tell me please where did you make the changes?

**Comment by ghemann** [comment]
lsd_slam/lsd_slam_core/src/IOWrapper/OpenCV/ImageDisplay_OpenCV.cpp
lines 119 and 125
I just replaced 'cv::waitKey(milliseconds)' with 'return 1'.

**Comment by gitunit** [comment]
@ghemann great, it finally works! thx. i should have asked earlier ;)

**Comment by hiankun** [comment]
@ghemann It works! Thank you. :-)

The viewer now shows the point cloud with the moving camera.
![lsd_slam_bag_test](https://cloud.githubusercontent.com/assets/7351282/10213228/d59fd54c-683c-11e5-9db9-003b9df3aaeb.png)

**Comment by ghost** [comment]
Hi @hiankun  
Can you tell me the camera you used and the lens? Did you use a global shutter camera?

**Comment by hiankun** [comment]
@yuanshucong Sorry for the so-late reply. The camera I used here is the Genius WideCam 1050. FYI.
