### ISSUE TITLE
Minimal Setup Problem: Couldn't find executable named live_slam

### ISSUE THREAD

**Issue by ningt** [tum-vision/lsd_slam#68]
Hi all,

I'm new to lsd slam and trying to get minimal setup work. However, I got error at line **rosrun lsd_slam_core live_slam image:=/image_raw camera_info:=/camera_info**, the error message is **Couldn't find executable named live_slam**.

Thanks in advance.

**Comment by Volcanoo** [comment]
@ningt Hey Tang, 

I'm new and have the same issue. Would you like to tell me how was this problem finally solved?

Thanks a lot.

**Comment by uzair789** [comment]
I managed to fix this problem by using catkin instead of rosmake. The following link provides step by step instructions:

http://visbot.blogspot.com/2014/11/tutorial-building-of-lsd-slam-on-ros.html
