### ISSUE TITLE
rospack could not be found, you cannot have rosbash features until you bootstrap ros

### ISSUE THREAD

**Issue by HChengmeng** [tum-vision/lsd_slam#79]
I am a new user. I follow the  "readme.md" to install on Ubuntu14.04.
When I goto this step
       2.2 ROS indigo + Ubuntu 14.04
             ...........
       echo "source ~/rosbuild_ws/setup.bash" >> ~/.bashrc
      bash
It report " rospack could not be found, you cannot have rosbash features until you bootstrap ros".
Is there an  way to solve this?
Thanks!

**Comment by HChengmeng** [comment]
I installed the  " ros-indigo-ros-base", and it works .

**Comment by gblikas** [comment]
This helped! +1
